FROM node:22-alpine3.20 AS base

ENV DIR /app
WORKDIR $DIR
ARG NPM_TOKEN

FROM base AS dev
ENV NODE_ENV=development
ENV CI=true

RUN npm install -g pnpm@latest-10

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

RUN echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ".npmrc" && \
    pnpm install --frozen-lockfile && \
    rm -f .npmrc

COPY prisma ./prisma/
COPY prisma.config.ts ./prisma.config.ts

COPY tsconfig*.json ./
COPY src src

RUN pnpm prisma generate

EXPOSE $PORT

CMD ["pnpm", "start:dev"]